on: push

name: Build and deploy Node app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - uses: actions/checkout@master
    - uses: "actions/aws/cli@master"
      with:
        args: "organizations list-accounts"
        secrets: ${{ secrets.AWS_ACCESS_KEY_ID }}, ${{ secrets.AWS_SECRET_ACCESS_KEY }}
   
    # install eb cli
    #- name: install EB CLI using pip (Python 2.7)
     # run: |
     #   python --version
      #  pip --version
     #   pip install awsebcli --upgrade --user
      #  eb --version    
        
  

