on: push

name: Build and deploy Node app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - uses: actions/checkout@master
    
    # install dependencies, build, and test
    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present
    - name: 'Login via Google Cloud Auth Action'
      uses = "actions/gcloud/auth@master"
      secrets = ["GCLOUD_AUTH"]
    - name: 'GCP List Clusters '
      uses = "actions/gcloud/cli@master"
      args = "container clusters list"
